on:
  pull_request:
    branches:
      - main
name: TOC Generator
jobs:
  generateTOC:
    runs-on: ubuntu-latest
    steps:
    - uses: meeDamian/github-release@2.0
	      with:
	      token: ${{ secrets.GITHUB_TOKEN }}
        TOC_TITLE: "**Inhaltsverzeichnis**"
        # Git commit name.
        COMMIT_NAME: "TOCGEN"
        CREATE_PR: false
        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/README.md"
